    
build:
  version: "1.0"
  
  

loans:
  message: "Welcome to Bank Loans related Production APIs "
  contactDetails:
    name: "abhi - Prod Lead"
    email: "abhi@gmail.com"
  onCallSupport:
    - (555) 326-1234
    - (555) 363-1345